image: python:latest

stages:
    - test_cov
    - test

test_cov:
    stage: test_cov
    tags:
        - docker
    script:
        - pip install coverage
        - coverage run -m unittest
        - coverage report
        - coverage xml
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml

test:
    stage: test
    tags:
        - docker
    script:
        - python3 -m unittest